version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: my-book
    depends_on:
      - mongodb
    volumes:
      - "../spiders:/app/spiders"
    working_dir: /app/spiders/Storage_MongoDB
    environment:
      - MONGO_URL=mongodb://mongodb:27017

volumes:
  mongo_data:
